Feature/favorite news
GuiPPDDH/CompassFirstApp pull request #4
Opened 2024-04-19 19:28 UTC by GuiPPDDH

Criado nova branch favorite_news;
Adicionado uma nova action para navegar para a listagem de notícias favoritas;
Adicionado uma tela de listagem de notícias favoritas.

2024-04-23 17:52 UTC, PedrozdR approved these changes

2024-04-24 12:32 UTC, PedrozdR requested changes

2024-04-24 12:32 UTC, PedrozdR commented on lib/components/molecules/news_details_profile_molecule/news_details_profile_molecule.dart
>              ),
Essa definição de cor para o desativado, é mesmo necessário ?

2024-04-24 12:32 UTC, PedrozdR commented on pubspec.yaml
> +  bloc: ^8.1.4
O próprio flutter_bloc deve adicionar essa lib nas suas dependências. Acho que n precisa adicionar ele tb. Olhando a doc, ele fala que só precisa adicionar o flutter_bloc msm.

2024-04-24 17:58 UTC, GuiPPDDH commented on lib/components/molecules/news_details_profile_molecule/news_details_profile_molecule.dart
>              ),
Não, e já fiz a remoção do atributo.

2024-04-24 17:59 UTC, GuiPPDDH commented on pubspec.yaml
> +  bloc: ^8.1.4
Removido importação do bloc e deixando apenas o flutter_bloc

2024-04-28 15:17 UTC, PedrozdR approved these changes

2024-04-30 12:39 UTC, merged